name: K8s App CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  ci:
    name: CI
    uses: kvncont/k8s-app/.github/workflows/reusable-ci.yaml@main
    with:
      java-version: 11
      sonar-project-key: kvncont_k8s-app
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
