name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  release-drafter:
    uses: kvncont/gh-workflows/.github/workflows/release-drafter.yml@main
