name: SonarCloud Scan
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    uses: kvncont/k8s-app/.github/workflows/reusable-sonarcloud-scan.yaml@main
